version: 1.17.{build}.0
image: Visual Studio 2019
platform:
- x86
- x64
- arm64
configuration:
- Release
install:
- cmd: git submodule -q update --init
- cmd: git clone -q https://github.com/microsoft/DMF.git C:\projects\DMF
before_build:
- ps: Invoke-WebRequest "https://github.com/nefarius/vpatch/releases/latest/download/vpatch.exe" -OutFile vpatch.exe
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\sys\ViGEmBus.vcxproj" --vcxproj.inf-time-stamp
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\sys\ViGEmBus.rc" --resource.file-version --resource.product-version
build_script:
- cmd: .\build.cmd
after_build:
- cmd: makecab.exe /f ViGEmBus_%PLATFORM%.ddf
artifacts:
- path: 'bin**\$(APPVEYOR_PROJECT_NAME)\*.inf'
- path: 'bin**\$(APPVEYOR_PROJECT_NAME)\*.sys'
- path: 'bin**\*.pdb'
- path: 'disk1\*.cab'
- path: 'bin**\*.msi'
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true